### ISSUE TITLE
Create a Docker-Compose file

### ISSUE THREAD

**Issue by emilasuska** [UVicMartletplace/martletplace#107]
## Feature Description

Make a Docker-Compose file to start all required services:
* Martletplace backend
* Elasticsearch

* Assign unique hostnames to each of the services.
* Expose the required ports
  * 80, 443 for http/https web server and backend
  * [TBD] port(s) for Elasticsearch
* Map volumes for configuration and data within docker containers for backend and search engine to local directories. Docker containers can be destroyed and recreated without loss of configuration and data.

relates: #xxx
blocked by: #xxx

## Problem You're Trying to Solve

Create a containerized environment that can be reproduced anywhere for production and local development.

## Acceptance Criteria
* The containers should run on any Mac or Linux host
* The containers can be deleted and recreated without any loss of configuration or data

**Comment by GDeane** [comment]
I believe that ResOps was setting this up for us. 

If you take a look at and checkout the master branch of martletplace, they already have a docker compose file set up with the frontend, backend, and search endpoints) (and Pull Requests are on the way to create the remaining endpoints, including elasticsearch):
![Image](https://github.com/UVicMartletplace/martletplace/assets/90437591/dcf632a3-8111-49a3-a7f4-ac53b2abd88e)

Good thing to ask ResOps about today though :)

**Comment by MNThomson** [comment]
duplicate: #22
