### ISSUE TITLE
PUT listing

### ISSUE THREAD

**Issue by emilasuska** [UVicMartletplace/martletplace#108]
## Feature Description

Create a new listing.

Create a Listing row in the database.
Create a Listing document in the search engine.

relates: #xxx
blocked by: #xxx

## Problem You're Trying to Solve

Part of basic CRUD functionality for Users and Listings.

## Acceptance Criteria
GET /api/listing/<id> returns the same information.
GET /api/search/?q="<description>" returns the listing in the result (near the top)

**Comment by GDeane** [comment]
Closed because backend is calling our reindexing API in #70
