### ISSUE TITLE
POST listing

### ISSUE THREAD

**Issue by emilasuska** [UVicMartletplace/martletplace#112]
## Feature Description

Modify a listing.

Modify a Listing row in the database.
Modify a Listing document in the search engine.

relates: #xxx
blocked by: #xxx

## Problem You're Trying to Solve

Part of basic CRUD functionality for Users and Listings.

## Acceptance Criteria 
GET /api/listing/id returns the modified listing information. 
GET /api/search/?q="old description" returns other listings or nothing
GET /api/search/?q="new description" returns listing in search results

**Comment by GDeane** [comment]
Closed because backend is calling reindexing API at #70
