### ISSUE TITLE
ZAP Security scan in CI

### ISSUE THREAD

**Issue by MNThomson** [UVicMartletplace/martletplace#139]
## Feature Description

Run [`OWASP ZAP`](https://github.com/zaproxy/action-baseline) in GitHub actions to scan the full application. Disable the "create issue" and enable "fail early" in the ci settings.

Investigate using the [full scan](https://github.com/zaproxy/action-full-scan) if it doesn't take much longer (or perhaps only on `master`)

## Problem You're Trying to Solve

Check for sane defaults in CI

**Comment by TobySMurray** [comment]
Completed ZAP testing locally, scan did not show any issues above the information severity level.
