### ISSUE TITLE
Create email server base project

### ISSUE THREAD

**Issue by kylestang** [UVicMartletplace/martletplace#21]
## Feature Description

We need to make an email server project and docker setup

## Problem You're Trying to Solve

We need to send recovery emails

## Related External Resources

none

**Comment by MNThomson** [comment]
Potential to use [`SMTP2GO`](https://www.smtp2go.com/pricing/) which has a good free plan. Self hosting email sucks. My thought would be to implement an endpoint on the datalayer that then sends the email _somewhere_. So either to SMTP2GO if we have an ENV VAR set or just echo'd out to the logs if not (saves us on sending a bunch of emails in load tests, etc)

**Comment by MNThomson** [comment]
Per conversation with @kylestang & @Scott-Kenning, we will create an internal api endpoint on the datalayer:
```
POST /api/email
{"recipient": "EMAIL@ADRESS", "subject": "SUBJECT", "body": "BODY OF EMAIL"}
```
This endpoint will then route the email to a legitimate SMTP server (in production) or console log the email contents (in development)
