### ISSUE TITLE
Optimize the performance of search

### ISSUE THREAD

**Issue by emilasuska** [UVicMartletplace/martletplace#315]
## Feature Description

The performance of the search should provide response times of 50ms-500ms when targeting 100k records (text).

## Problem You're Trying to Solve

Optimize the speed that search results are returned. 

Also the precision (number of relevant documents retrieved/number of total documents retrieved) of the search engine should be 0.5 or higher as to provide relevant search results.

## Related External Resources

Section 5.1.1 in the SRS:
https://docs.google.com/document/d/1GpUhxS3qDxvpE2PmIyHJPRil5Z_i3-Qbs8K9_TxBFbU/edit#heading=h.9h1nydowmk65

**Comment by GDeane** [comment]
See Resops PRs, 27x speedup by creating sustained connections (9x) and running SQL in the background (3x)
