### ISSUE TITLE
Optimize the scalability of the search engine

### ISSUE THREAD

**Issue by emilasuska** [UVicMartletplace/martletplace#316]
## Feature Description

The search engine should be scalable as to not degrade performance with up to 1,000,000 requests across 100,000 concurrent users.

## Problem You're Trying to Solve

The search engine should be able to handle numerous requests from multiple users and still perform well in terms of response time and precision.

## Related External Resources

Section 5.1.1 of SRS:
https://docs.google.com/document/d/1GpUhxS3qDxvpE2PmIyHJPRil5Z_i3-Qbs8K9_TxBFbU/edit#heading=h.9h1nydowmk65

**Comment by GDeane** [comment]
Gone up to 50k items in elasticsearch
