### ISSUE TITLE
Search for sellers and view their listings

### ISSUE THREAD

**Issue by emilasuska** [UVicMartletplace/martletplace#35]
## Feature Description
Search for sellers and view their listings

## Problem You're Trying to Solve
As a user, I want to search for sellers, so that I can find specific users and view their listings.

## Related External Resources

SRS 1.0 Section 5.1.4

**Comment by GDeane** [comment]
I believe this ticket is encompassed in ticket #50 

See the "searchType" parameter in the Return Search Results API endpoint in [SRS 1.0](https://docs.google.com/document/d/1DNqexMBf4MpYPCxWsT3plUDAjDSbdJwUzw-UyZX-vDs/edit?usp=sharing)
