### ISSUE TITLE
status 404 should not be returned for "items not found"

### ISSUE THREAD

**Issue by abookout** [UVicMartletplace/martletplace#354]
These should almost definitely all be 200, if not then probably 400

![Image](https://github.com/UVicMartletplace/martletplace/assets/19939886/c6cb5904-14bf-4ad4-bae7-b1451db74ab4)

**Comment by bmachado18** [comment]
I've done some research. I guess for a resource that is missing, the result should be status code 204: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/204
