### ISSUE TITLE
Create View Personal Profile Component

### ISSUE THREAD

**Issue by CaelumD25** [UVicMartletplace/martletplace#62]
## Feature Description

This is the component that contains a the current users profile with the edit and logout functionality("Your Profile")

- Params:
    -  JSON Object: [User Profile(OpenAPI spec)](http://market.lebl.ca/openapi/#/:~:text=LoginRequest-,UserProfile,-%7B)

relates: #76

## Problem You're Trying to Solve

We need a component that displays a users profile information.

## Related External Resources

![Image](https://github.com/UVicMartletplace/martletplace/assets/54737724/d5e4fcac-4c30-45fd-aa66-8d4482845013)

**Comment by sejal-agarwal** [comment]
Reopening this because I need to add a couple things to allow users to view other user profiles
