### ISSUE TITLE
Set up Database Tables

### ISSUE THREAD

**Issue by Scott-Kenning** [UVicMartletplace/martletplace#64]
## Feature Description
Initial creation of the database tables for each data entity

## Problem You're Trying to Solve
There's no database tables

## Related External Resources
https://docs.google.com/document/d/1DNqexMBf4MpYPCxWsT3plUDAjDSbdJwUzw-UyZX-vDs/edit#heading=h.vbv6udt3y8om Section 4.2

**Comment by bmachado18** [comment]
Decided against ORM because:
- Not necessary for this simple database
- Adds unecessary overhead

Need to think about cascades.
- if a user is deleted, do we deleting their listings?

**Comment by bmachado18** [comment]
notes:
- not worrying about triggers yet, want to get tables setup
- using serials so auto increments on creation
- creation timestamps default to current time
- Not inserting values here; should do that outside the initdb file
