### ISSUE TITLE
Add search history functionality

### ISSUE THREAD

**Issue by Scott-Kenning** [UVicMartletplace/martletplace#97]
## Feature Description
Create GET and DELETE endpoints for the search history which will be added to postgres by the algo team

## Problem You're Trying to Solve
Users need to be able to view and delete their search history

## Related External Resources
[section 4.4.1](https://docs.google.com/document/d/1DNqexMBf4MpYPCxWsT3plUDAjDSbdJwUzw-UyZX-vDs/edit#heading=h.vbv6udt3y8om)

**Comment by bmachado18** [comment]
using the jwt token instead of using a parameter
